### ISSUE TITLE
Modification to Latex table costruction

### ISSUE THREAD

**Issue by nicolarici** [aiunibs/unibs_utils#3]
**Impossible to add a NO-float data-type**
Cause the precision parameter, it is impossibile to insert a NO-float value

**No \hline**
Insert a flag that put a \hline at the end of the row to build a full table

**Escape the Latex special char**
If you insert a string with characters like "&", "%", "$", ecc..., the Latex compiler will crash. 
Will be helpful if all the special character were escaped with "\" (example "& -> \&")

special chars list: ["&", "%", "$", "#", "_", "{", "}", "~", "^", "\"]

**Comment by mattia93** [comment]
# **Tasks**:

-  Handle non float data
-  Add \\hline
-  Add escape for special characters


## **Handle non float data**
**Is your feature request related to a problem? Please describe.**
Latex table only works with `float` data type. e.g. I get format error every time I insert `str` data type it raises 
```python
Unknown format code 'f' for object of type 'numpy.str_'
```

**Describe the solution you'd like**
I would like to insert `str` in the table

## **Add \\hline**
**Is your feature request related to a problem? Please describe.**
After creating a LaTeX table I have to add `\hline` manually after each row

**Describe the solution you'd like**
I would like to have an option to add the `\hline` after each row


## **Add escape for special characters**
**Is your feature request related to a problem? Please describe.**
When adding strings in labels that contain special characters such as *%*, *&*, etc. it causes compilation problems in the LaTex editor.

**Describe the solution you'd like**
I would like to automatically escape those characters
