### ISSUE TITLE
Add range to axes

### ISSUE THREAD

**Issue by nicolarici** [aiunibs/unibs_utils#5]
**Is your feature request related to a problem? Please describe.**
I can't customize the axes range.

**Describe the solution you'd like**
Add parameters to the function _plots.get_line_plot_ to set the intervals for the two axes.

**Comment by aiunibs** [comment]
# Task

Allow y axis customization 

**Describe the solution you'd like**
Add `yticks` and `yticks_labels` to `get_line_plot` method

# Note 
In the method `get_line_plot`, x axis can already be customized using `xticks` and `ticks_labels` parameters which allow respectively to change the ticks on the x axis and to change the labels assigned to those ticks.
